version: '3.7'

services:
  imap:
     image: imap
     hostname: imap
     restart: unless-stopped
     build:
       context: ./imap
       args:
         vmail_gid: 0
         vmail_uid: 503
         VMAIL_GROUP: root
         VMAIL_USER : vmail
     environment:
        - LDAP_HOSTS=${LDAP_HOSTS}
        - LDAP_PASSWORD=${LDAP_PASSWORD}
        - LDAP_USER=${LDAP_USER}
        - LDAP_BASE=${LDAP_BASE}
        - LDAP_USER_FILTER=${LDAP_USER_FILTER}
        - LDAP_PASS_FILTER=${LDAP_PASS_FILTER}
        - LDAP_ITERATE_FILTER=${LDAP_ITERATE_FILTER}
        # - LDAP_USER_FILTER="(&(|(objectclass=posixAccount))(&(memberof=cn=localMail,ou=groups,dc=elternserver,dc=de)(|(mail=%u)(|(gosaMailAlternateAddress=%u))))"
     volumes:
       # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
       - /data/${DOMAIN}/vmail:/var/vmail
       # - log:/var/log
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "143:1143"
       - "993:1993"
       - "4190:4190"
       # - "2525:2525"
     extra_hosts:
        # - "murg.elternserver.local:10.100.101.16"
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: faudin.de
     hostname: imap
     labels:
       - "traefik.enable=false"
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey
     networks:
       #  mail:
       # ipv4_address: 172.26.0.3
       # aliases:
       #  - imap
       services:
          ipv4_address: $IMAP_IP
          aliases:
            - imap



  exim-external:
    image: exim
    hostname: exim-external
    restart: unless-stopped
    build:
      context: ./exim
      args:
        EXIM_GID: 0
        EXIM_GROUP: root
        EXIM_USER: exim
        EXIM_UID: 1024
        EXIM_VERSION: 4.94

        # EXIM_EXTERNAL_IP: ${EXIM_IP}
        EXIM_VERSION: exim-4.94+fixes
        # EXIM_SOURCE: https://github.com/EXIM/EXIM/archive/EXIM-${EXIM_VERSION}.tar.gz
    volumes:
      # - /data/${DOMAIN}/mail-external/log:/var/log
        # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
    environment:
       - LDAP_HOSTS=${LDAP_HOSTS}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
       - LDAP_USER=${LDAP_USER}
       - LDAP_BASE=${LDAP_BASE}
       - LDAP_USER_FILTER=${LDAP_USER_FILTER}
       - "EXIM_PORTS=1025 : 1465 : 1587"
       - EXIM_TLS_ON_CONNECT_PORTS=1465
       - DOMAIN=${DOMAIN}
       # - SUBMISSION_PORT=1587
    extra_hosts:
       # - "murg.elternserver.local:10.100.101.16"
       - "ldap.${DOMAIN}.de:${LDAP_IP}"
    domainname: faudin.de

    labels:
      - "traefik.enable=false"
    secrets:
       - letsencrypt-cert
       - letsencrypt-fullchain
       - source: letsencrypt-privkey
         target: letsencrypt-privkey
    ports:
      - "25:1025"
      - "587:1587"
    networks:
        services:
          ipv4_address: ${EXIM_EXTERNAL_IP}
          aliases:
            - exim


  redis:
    image: redis
    hostname: redis
    restart: unless-stopped
    build:
      context: ./redis
      args:
        redis_gid: 0
        redis_uid: 6379
        REDIS_GROUP: root
        REDIS_USER : redis
        REDIS_IP: ${REDIS_IP}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    # environment:
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
      - /data/${DOMAIN}/redis:/data
      # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
    networks:
      services:
        ipv4_address: ${REDIS_IP}
        aliases:
          - redis



volumes:
    log: {}

secrets:
        letsencrypt-cert:
           file: /etc/letsencrypt-readers/cert.pem
        letsencrypt-fullchain:
           file: /etc/letsencrypt-readers/fullchain.pem
        letsencrypt-privkey:
           file: /etc/letsencrypt-readers/privkey.pem

networks:
   mail:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.26.0.0/24
   traefik:
     external: true
   services:
     external: true
