version: '3.7'


services:
  imap:
     image: joergschulz/imap
     hostname: imap
     container_name: imap
     restart: unless-stopped
     build:
       context: ./imap
       args:
         vmail_gid: ${vmail_gid:-0}
         vmail_uid: ${vmail_uid:-1001}
         VMAIL_GROUP: ${VMAIL_GROUP:-root}
         VMAIL_USER : ${VMAIL_USER:-vmail}
         dovecot_branch : ${dovecot_branch:-release-2.3.18.1}
         dovecot_tag : ${dovecot_tag:-2.3.15}
         pigeonhole_branch : ${pigeonhole_branch:-release-0.5.18.1}
     environment:
        - LDAP_HOSTS=${LDAP_HOSTS}
        - LDAP_PASSWORD=${LDAP_PASSWORD}
        - LDAP_USER=${LDAP_USER}
        - LDAP_BASE=${LDAP_BASE}
        - LDAP_USER_FILTER=${LDAP_USER_FILTER}
        - LDAP_PASS_FILTER=${LDAP_PASS_FILTER}
        - LDAP_ITERATE_FILTER=${LDAP_ITERATE_FILTER}
        - IMAP_AUTH_VERBOSE=${IMAP_AUTH_VERBOSE:-no}
        - IMAP_MAIL_DEBUG=${IMAP_MAIL_DEBUG:-no}
        - DOMAIN=${DOMAIN}
        - SMTPHOST=exim-int-mailout:1587
        - IMAP_REPLICA_SERVER=${IMAP_REPLICA_SERVER}
        - IMAP_REPLICA_PORT=${IMAP_REPLICA_PORT}
        - IMAP_REPLICA_PASSWORD=${IMAP_REPLICA_PASSWORD}
     volumes:
       # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
       - /data/${DOMAIN}/vmail:/var/vmail
       # - log:/var/log
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "143:1143"
       - "993:1993"
       - "4190:4190"
       - $IMAP_REPLICA_PORT:$IMAP_REPLICA_PORT
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"
         mode: non-blocking
     extra_hosts:
        - "m.datilo.de:10.100.101.16"
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: ${DOMAIN}.de
     labels:
       - "traefik.enable=false"
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey

     networks:
       #  mail:
       # ipv4_address: 172.26.0.3
       # aliases:
       #  - imap
       services:
          ipv4_address: $IMAP_IP
          aliases:
            - imap

  rspam:
     image: joergschulz/rspam
     restart: unless-stopped
     build:
       context: ./rspam
       args:
         RSPAM_gid: 0
         RSPAM_uid: 1001
         RSPAM_GROUP: root
         RSPAM_USER : rspamd
         RSPAM_IP: ${RSPAM_IP}
         RSPAM_REDIS_DB: 7
     depends_on:
       - mail-redis
       - clamav
     volumes:
       - /data/${DOMAIN}/rspam:/var/lib/rspamd
       - /etc/localtime:/etc/localtime:ro
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"
         mode: non-blocking
     extra_hosts:
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: ${DOMAIN}.de
     hostname: rspam
     container_name: rspam
     environment:
       - REDIS_PASSWORD=${REDIS_PASSWORD}
       - REDIS_PORT=${REDIS_PORT}
       - RSPAM_GROUP=root
       - RSPAM_USER=rspamd
       - RSPAM_enable_password=${RSPAM_enable_password}
       - RSPAM_password=${RSPAM_password}
       - RSPAM_REDIS_DB=7
       - RSPAM_IP=${RSPAM_IP}
       - CLAMAV_IP=${CLAMAV_IP}
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.rule=Host(`rspam.${DOMAIN}.de`)"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.tls=true"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.entrypoints=websecure"
       - "traefik.docker.network=traefik"
       - traefik.port=11334
       - traefik.backend=rspam
     networks:
       services:
        ipv4_address: ${RSPAM_IP}
        aliases:
         - rspam
       traefik:
         aliases:
           - rspam

  exim-external:
    image: joergschulz/exim
    hostname: exim-external
    container_name: exim-external
    restart: unless-stopped
    depends_on:
      - rspam
    build:
      context: ./exim
      args:
        EXIM_GID: 0
        EXIM_GROUP: root
        EXIM_USER: exim
        EXIM_UID: 1001
        EXIM_VERSION: 4.94
        DOMAIN: ${DOMAIN}

        # EXIM_EXTERNAL_IP: ${EXIM_IP}
        EXIM_VERSION: exim-4.94+fixes
        # EXIM_SOURCE: https://github.com/EXIM/EXIM/archive/EXIM-${EXIM_VERSION}.tar.gz
    volumes:
      # - /data/${DOMAIN}/mail-external/log:/var/log
        # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - ${EXIM_EXTERNAL_SPOOL:-/data/exim-external/spool}:/var/spool/exim
      - ${EXIM_EXTERNAL_LOG:-/data/exim-external/log}:/var/log/exim
    environment:
       - LDAP_HOSTS=${LDAP_HOSTS}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
       - LDAP_USER=${LDAP_USER}
       - LDAP_BASE=${LDAP_BASE}
       - EXIM_LDAP_USER_FILTER=${EXIM_LDAP_USER_FILTER}
       - "EXIM_PORTS=1025 : 1465 : 1587"
       - EXIM_TLS_ON_CONNECT_PORTS=1465
       - EXIM_LOCAL_DOMAINS=${EXIM_LOCAL_DOMAINS}
       - DOMAIN=${DOMAIN}
    extra_hosts:
       - "ldap.${DOMAIN}.de:${LDAP_IP}"
       # - "imap.${DOMAIN}.de:${IMAP_IP}" # DNS would point to external interface. Not reachable.
    domainname: ${DOMAIN}.de
    container_name: exim
    labels:
      - "traefik.enable=false"
    secrets:
       - letsencrypt-cert
       - letsencrypt-fullchain
       - source: letsencrypt-privkey
         target: letsencrypt-privkey
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
    ports:
      - "25:1025"
      - "587:1587"
      - "465:1465"
    networks:
        services:
          ipv4_address: ${EXIM_EXTERNAL_IP}
          aliases:
            - exim

  clamav:
    image: joergschulz/docker-clamav
    hostname: clamav
    build:
      context: ./clamav
      args:
        CLAMAV_gid: 0
        CLAMAV_uid: 1001
        CLAMAV_GROUP: root
        CLAMAV_USER : clamav
    container_name: clamav
    restart: always
    domainname: ${DOMAIN}.de
    environment:
       - CLAMAV_IP=${CLAMAV_IP}
    volumes:
      # - clam:/var/lib/clamav
      # - /data/${DOMAIN}/clamav:/var/lib/clamav
      - ${CLAMAVLIB:-/data/clamav}:/var/lib/clamav
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
    networks:
        services:
          ipv4_address: ${CLAMAV_IP}
          aliases:
            - clamav


  mail-redis:
    image: joergschulz/redis
    hostname: mail-redis
    restart: unless-stopped
    build:
      context: ./redis
      args:
        redis_gid: 0
        redis_uid: 1001
        REDIS_GROUP: root
        REDIS_USER : redis
    volumes:
      # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
      - /data/${DOMAIN}/redis:/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
    environment:
      - REDIS_IP=${REDIS_IP}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PRODECTED_MODE=${REDIS_PRODECTED_MODE:-yes}
      - REDIS_PORT=${REDIS_PORT}
    container_name: mail-redis
    # sorry, you must change something manually here if you want externals to (not) use redis.
    # the protected mode flag doesn't work. If you want to restrict access to docker-internal, uncomment the following 2 lines
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      services:
        ipv4_address: ${REDIS_IP}
        aliases:
          - mail-redis

  exim-int-mailout:
    image: joergschulz/exim-int-mailout
    hostname: exim-int-mailout
    container_name: exim-int-mailout
    restart: unless-stopped
    depends_on:
      - rspam
    build:
      context: ./exim-int-mailout
      args:
        EXIM_GID: 0
        EXIM_GROUP: root
        EXIM_USER: exim
        EXIM_UID: 1001
        # EXIM_VERSION: 4.94

        # EXIM_EXTERNAL_IP: ${EXIM_IP}
        # EXIM_VERSION: exim-4.94+fixes
        # EXIM_SOURCE: https://github.com/EXIM/EXIM/archive/EXIM-${EXIM_VERSION}.tar.gz
    volumes:
      # - /data/${DOMAIN}/mail-external/log:/var/log
        # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - ${EXIM_INT_MAILOUT_SPOOL:-/data/exim-int-mailout/spool}:/var/spool/exim
      - ${EXIM_INT_MAILOUT_LOG:-/data/exim-int-mailout/log}:/var/log/exim
      - ${MM3_DATA_DIR}:/opt/mailman/
    environment:
       - LDAP_HOSTS=${LDAP_HOSTS}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
       - LDAP_USER=${LDAP_USER}
       - LDAP_BASE=${LDAP_BASE}
       - EXIM_LDAP_USER_FILTER=${EXIM_LDAP_USER_FILTER}
       - "EXIM_PORTS=1025 : 1465 : 1587"
       - EXIM_TLS_ON_CONNECT_PORTS=1465
       - EXIM_LOCAL_DOMAINS=${EXIM_LOCAL_DOMAINS}
       - DOMAIN=${DOMAIN}
       - EXIM_RELAY_HOSTS=${EXIM_RELAY_HOSTS}
       - EXIM_INT_MAILOUT_LDAP_AUTH=${EXIM_INT_MAILOUT_LDAP_AUTH}
    extra_hosts:
       - "ldap.${DOMAIN}.de:${LDAP_IP}"
       - mailout.${DOMAIN}.de:${EXIM_EXTERNAL_IP}
       - smarthost.${DOMAIN}.de:${EXIM_SMARTHOST_MAILOUT:-mailout.fau}

       # - "imap.${DOMAIN}.de:${IMAP_IP}" # DNS would point to external inerface. Not reachable.
    domainname: ${DOMAIN}.de
    labels:
      - "traefik.enable=false"
    secrets:
       - dkim-privkey
       - letsencrypt-cert
       - letsencrypt-fullchain
       - source: letsencrypt-privkey
         target: letsencrypt-privkey
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
    ports:
      # - "2526:1025"
      - "2587:1587"
      # - "1465:1465"
    networks:
        services:
          ipv4_address: ${EXIM_INT_MAILOUT_IP:-172.20.0.9}
          aliases:
            - exim-int-mailout
    dns:
      - dnsmasq

  exim-ext-mailout:
    image: joergschulz/exim-mailout
    hostname: mailout.${DOMAIN}.de # exim-ext-mailout
    container_name: exim-ext-mailout
    restart: unless-stopped
    depends_on:
      - rspam
    build:
      context: ./exim-ext-mailout
      args:
        EXIM_GID: 0
        EXIM_GROUP: root
        EXIM_USER: exim
        EXIM_UID: 1001
    volumes:
      # - /data/${DOMAIN}/mail-external/log:/var/log
        # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - ${EXIM_EXT_MAILOUT_SPOOL:-/data/exim-ext-mailout/spool}:/var/spool/exim
      - ${EXIM_EXT_MAILOUT_LOG:-/data/exim-ext-mailout/log}:/var/log/exim
    environment:
       # - LDAP_HOSTS=${LDAP_HOSTS}
       # - LDAP_PASSWORD=${LDAP_PASSWORD}
       # - LDAP_USER=${LDAP_USER}
       # - LDAP_BASE=${LDAP_BASE}
       # - EXIM_LDAP_USER_FILTER=${EXIM_LDAP_USER_FILTER}
       - "EXIM_PORTS=1025 : 1465 : 1587"
       - EXIM_TLS_ON_CONNECT_PORTS=1465
       - EXIM_LOCAL_DOMAINS=${EXIM_LOCAL_DOMAINS}
       - DOMAIN=${DOMAIN}
       - EXIM_RELAY_HOSTS=${EXIM_RELAY_HOSTS}
       - EXIM_WHITELIST_NET=${EXIM_WHITELIST_NET:-172.20.0.0/16}
       - EXIM_DKIM_SELECTOR=${EXIM_DKIM_SELECTOR}
    # extra_hosts:
       # - "ldap.${DOMAIN}.de:${LDAP_IP}"
       # - "imap.${DOMAIN}.de:${IMAP_IP}" # DNS would point to external inerface. Not reachable.
    domainname: faudin.de
    labels:
      - "traefik.enable=false"
    secrets:
       - dkim-privkey
       - letsencrypt-cert
       - letsencrypt-fullchain
       - source: letsencrypt-privkey
         target: letsencrypt-privkey
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
    ports:
    #  - "2526:1025"
    - "1587:1587"
    #  - "1465:1465"
    networks:
        services:
          ipv4_address: ${EXIM_EXT_MAILOUT_IP}
          aliases:
            - exim-ext-mailout

  mail-dnsmasq:
    image: joergschulz/dnsmasq
    hostname: mail-dnsmasq
    restart: unless-stopped
    build:
      context: ./dnsmasq
      args:
        DNSMASQ_GID: 1001
        DNSMASQ_UID: 1001
        DNSMASQ_GROUP: dnsmasq
        DNSMASQ_USER : dnsmasq
    volumes:
      # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
      - /data/${DOMAIN}/dnsmasq/dnsmasq.conf /etc/dnsmasq.conf
      - /data/${DOMAIN}/dnsmasq/dnsmasq.d /etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #  - 53:53
    container_name: mail-dnsmasq
    networks:
      services:
        ipv4_address: ${DNSMASQ_IP}
        aliases:
          - mail-dnsmasq
    # THIS is the place where you need to put all your DNS overwrites
    extra_hosts:
       - "ldap.${DOMAIN}.de:${LDAP_IP}"
       - mailout.${DOMAIN}.de:${EXIM_EXTERNAL_IP}
       - smarthost.${DOMAIN}.de:${EXIM_SMARTHOST_MAILOUT_IP:-172.20.0.8}


volumes:
    log: {}
secrets:
        letsencrypt-cert:
           file: /etc/letsencrypt-readers/cert.pem
        letsencrypt-fullchain:
           file: /etc/letsencrypt-readers/fullchain.pem
        letsencrypt-privkey:
           file: /etc/letsencrypt-readers/privkey.pem
        dkim-privkey:
            file: .certs/dkim-faudin.de-private

networks:
   traefik:
     external: true
   services:
     external: true
