version: '3.7'

services:
  imap:
     image: imap
     hostname: imap
     restart: unless-stopped
     build:
       context: ./imap
       args:
         vmail_gid: 0
         vmail_uid: 503
         VMAIL_GROUP: root
         VMAIL_USER : vmail
     environment:
        - LDAP_HOSTS=${LDAP_HOSTS}
        - LDAP_PASSWORD=${LDAP_PASSWORD}
        - LDAP_USER=${LDAP_USER}
        - LDAP_BASE=${LDAP_BASE}
        - LDAP_USER_FILTER=${LDAP_USER_FILTER}
        - LDAP_PASS_FILTER=${LDAP_PASS_FILTER}
        - LDAP_ITERATE_FILTER=${LDAP_ITERATE_FILTER}
        # - LDAP_USER_FILTER="(&(|(objectclass=posixAccount))(&(memberof=cn=localMail,ou=groups,dc=elternserver,dc=de)(|(mail=%u)(|(gosaMailAlternateAddress=%u))))"
     volumes:
       # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
       - /var/vmail:/var/vmail
       # - log:/var/log
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "143:1143"
       - "993:1993"
       - "4190:4190"
       # - "2525:2525"
     extra_hosts:
        # - "murg.elternserver.local:10.100.101.16"
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: faudin.de
     hostname: imap
     labels:
       - "traefik.enable=false"
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey
     networks:
       #  mail:
       # ipv4_address: 172.26.0.3
       # aliases:
       #  - imap
       services:
          ipv4_address: 172.20.0.5
          aliases:
            - imap



volumes:
    log: {}

secrets:
        letsencrypt-cert:
           file: /etc/letsencrypt-readers/cert.pem
        letsencrypt-fullchain:
           file: /etc/letsencrypt-readers/fullchain.pem
        letsencrypt-privkey:
           file: /etc/letsencrypt-readers/privkey.pem

networks:
   mail:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.26.0.0/24
   traefik:
     external: true
   services:
     external: true
