version: '3.7'

services:
  imap:
     image: imap
     hostname: imap
     restart: unless-stopped
     build:
       context: ./imap
       args:
         vmail_gid: 0
         vmail_uid: 503
         VMAIL_GROUP: root
         VMAIL_USER : vmail
     environment:
        - LDAP_HOSTS=${LDAP_HOSTS}
        - LDAP_PASSWORD=${LDAP_PASSWORD}
        - LDAP_USER=${LDAP_USER}
        - LDAP_BASE=${LDAP_BASE}
        - LDAP_USER_FILTER=${LDAP_USER_FILTER}
        - LDAP_PASS_FILTER=${LDAP_PASS_FILTER}
        - LDAP_ITERATE_FILTER=${LDAP_ITERATE_FILTER}
        # - LDAP_USER_FILTER="(&(|(objectclass=posixAccount))(&(memberof=cn=localMail,ou=groups,dc=elternserver,dc=de)(|(mail=%u)(|(gosaMailAlternateAddress=%u))))"
     volumes:
       # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
       - /data/${DOMAIN}/vmail:/var/vmail
       # - log:/var/log
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "143:1143"
       - "993:1993"
       - "4190:4190"
       # - "2525:2525"
     extra_hosts:
        # - "murg.elternserver.local:10.100.101.16"
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: faudin.de
     hostname: imap
     labels:
       - "traefik.enable=false"
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey
     networks:
       #  mail:
       # ipv4_address: 172.26.0.3
       # aliases:
       #  - imap
       services:
          ipv4_address: $IMAP_IP
          aliases:
            - imap

  rspam:
     image: rspam
     restart: unless-stopped
     build:
       context: ./rspam
       args:
         RSPAM_gid: 0
         RSPAM_uid: 1001
         RSPAM_GROUP: root
         RSPAM_USER : rspamd
         RSPAM_IP: ${RSPAM_IP}
         RSPAM_REDIS_DB: 7

     depends_on:
       - redis
       - clamav
     volumes:
       # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
       # - /usr/local/src/docker/mail/etc/rspamd:/etc/rspamd
       # - log:/var/log
       - /data/${DOMAIN}/rspam:/var/lib/rspamd
       - /etc/localtime:/etc/localtime:ro
     ports:
       - 11334:11334
     extra_hosts:
        - "ldap.${DOMAIN}.de:${LDAP_IP}"
     domainname: ${DOMAIN}.de
     hostname: rspam
     environment:
       - REDIS_PASSWORD=${REDIS_PASSWORD}
       - RSPAM_GROUP=root
       - RSPAM_USER=rspamd
       - RSPAM_enable_password=${RSPAM_enable_password}
       - RSPAM_password=${RSPAM_password}
       - RSPAM_REDIS_DB=7
       - RSPAM_IP=${RSPAM_IP}
       - CLAMAV_IP=${CLAMAV_IP}
     secrets:
        - letsencrypt-cert
        - letsencrypt-fullchain
        - source: letsencrypt-privkey
          target: letsencrypt-privkey
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.rule=Host(`rspam.${DOMAIN}.de`)"
       # - "traefik.http.routers.api.middlewares=auth"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.tls=true"
       - "traefik.http.routers.rspam_${DOMAIN}_tls.entrypoints=websecure"
       # - "traefik.http.middlewares.auth.basicauth.users=js:$$apr1$$x/KGmZcY$$lKC.FmZGenhbjMu1LrTFI."
       - "traefik.docker.network=traefik"
       - traefik.port=11334
       - traefik.backend=rspam
       # - "traefik.http.routers.api.middlewares=auth"
       # - "traefik.http.middlewares.auth.basicauth.users=js:$$apr1$$x/KGmZcY$$lKC.FmZGenhbjMu1LrTFI."


     networks:
       services:
        ipv4_address: ${RSPAM_IP}
        aliases:
         - rspam
       traefik:
         aliases:
           - rspam

  exim-external:
    image: joergmschulz/exim
    hostname: exim-external
    restart: unless-stopped
    depends_on:
      - rspam
    build:
      context: ./exim
      args:
        EXIM_GID: 0
        EXIM_GROUP: root
        EXIM_USER: exim
        EXIM_UID: 1024
        EXIM_VERSION: 4.94

        # EXIM_EXTERNAL_IP: ${EXIM_IP}
        EXIM_VERSION: exim-4.94+fixes
        # EXIM_SOURCE: https://github.com/EXIM/EXIM/archive/EXIM-${EXIM_VERSION}.tar.gz
    volumes:
      # - /data/${DOMAIN}/mail-external/log:/var/log
        # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
    environment:
       - LDAP_HOSTS=${LDAP_HOSTS}
       - LDAP_PASSWORD=${LDAP_PASSWORD}
       - LDAP_USER=${LDAP_USER}
       - LDAP_BASE=${LDAP_BASE}
       - EXIM_LDAP_USER_FILTER=${EXIM_LDAP_USER_FILTER}
       - "EXIM_PORTS=1025 : 1465 : 1587"
       - EXIM_TLS_ON_CONNECT_PORTS=1465
       - EXIM_LOCAL_DOMAINS=${EXIM_LOCAL_DOMAINS}
       - DOMAIN=${DOMAIN}
       # - SUBMISSION_PORT=1587
    extra_hosts:
       # - "murg.elternserver.local:10.100.101.16"
       - "ldap.${DOMAIN}.de:${LDAP_IP}"
       - "imap.${DOMAIN}.de:${IMAP_IP}" # will be pulled from LDAP
    domainname: faudin.de

    labels:
      - "traefik.enable=false"
    secrets:
       - letsencrypt-cert
       - letsencrypt-fullchain
       - source: letsencrypt-privkey
         target: letsencrypt-privkey
    ports:
      - "25:1025"
      - "587:1587"
      - "465:1465"
    networks:
        services:
          ipv4_address: ${EXIM_EXTERNAL_IP}
          aliases:
            - exim
  clamav:
    image: joergmschulz/docker-clamav
    hostname: clamav
    build:
      context: ./clamav
      args:
        CLAMAV_gid: 0
        CLAMAV_uid: 1001
        CLAMAV_GROUP: root
        CLAMAV_USER : clamav
    container_name: clamav
    restart: always
    environment:
       - CLAMAV_IP=${CLAMAV_IP}
    volumes:
      # - clam:/var/lib/clamav
      # - /data/${DOMAIN}/clamav:/var/lib/clamav
      - ${CLAMAVLIB:-/data/clamav}:/var/lib/clamav
    networks:
        services:
          ipv4_address: ${CLAMAV_IP}
          aliases:
            - clamav


  redis:
    image: redis
    hostname: redis
    restart: unless-stopped
    build:
      context: ./redis
      args:
        redis_gid: 0
        redis_uid: 6379
        REDIS_GROUP: root
        REDIS_USER : redis

    # environment:
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      # - /etc/ldap/ldap.conf:/etc/ldap/ldap.conf
      - /data/${DOMAIN}/redis:/data
      # - log:/var/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_IP=${REDIS_IP}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: redis
    networks:
      services:
        ipv4_address: ${REDIS_IP}
        aliases:
          - redis




volumes:
    log: {}

secrets:
        letsencrypt-cert:
           file: /etc/letsencrypt-readers/cert.pem
        letsencrypt-fullchain:
           file: /etc/letsencrypt-readers/fullchain.pem
        letsencrypt-privkey:
           file: /etc/letsencrypt-readers/privkey.pem

networks:
   traefik:
     external: true
   services:
     external: true
